name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允許手動觸發

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        cd ../backend
        npm ci

    - name: Build frontend
      run: |
        cd frontend
        npm run build
      env:
        VITE_API_URL: https://yunshui-backend1.onrender.com/api
        VITE_WS_URL: https://yunshui-backend1.onrender.com
        VITE_NODE_ENV: production

    - name: Build backend
      run: |
        cd backend
        npm run build

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./frontend
        vercel-args: '--prod'

    - name: Trigger Render Deploy
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
      if: ${{ secrets.RENDER_DEPLOY_HOOK }}

    - name: Create deployment status
      run: |
        echo "# Deployment Status" > DEPLOYMENT_STATUS.md
        echo "" >> DEPLOYMENT_STATUS.md
        echo "## Deployment Time: $(date)" >> DEPLOYMENT_STATUS.md
        echo "## Commit: ${{ github.sha }}" >> DEPLOYMENT_STATUS.md
        echo "## Status: ✅ Deployed" >> DEPLOYMENT_STATUS.md
        echo "" >> DEPLOYMENT_STATUS.md
        echo "### Frontend (Vercel)" >> DEPLOYMENT_STATUS.md
        echo "- Status: ✅ Deployed" >> DEPLOYMENT_STATUS.md
        echo "" >> DEPLOYMENT_STATUS.md
        echo "### Backend (Render)" >> DEPLOYMENT_STATUS.md
        echo "- Status: ✅ Deploy triggered" >> DEPLOYMENT_STATUS.md